package com.otoki.powersales._migration.sf.service

import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import com.otoki.powersales.platform.common.config.QueryDslConfig
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase
import org.springframework.context.annotation.Import
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.context.TestPropertySource
import org.springframework.transaction.annotation.Transactional

/**
 * Stage 2 Service 통합 테스트 — H2 PostgreSQL 호환 모드 + native query 동작 검증.
 *
 * `@DataJpaTest` 슬라이스 + H2 url 을 PostgreSQL 호환 모드로 override.
 * powersales schema + 4개 minimal 테이블을 BeforeEach 로 직접 생성한다 (Flyway 미사용).
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
@Import(QueryDslConfig::class)
@TestPropertySource(
    properties = [
        "spring.datasource.url=jdbc:h2:mem:sfmigration_stage2_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false",
    ],
)
@DisplayName("SfMigrationStage2Service 통합 테스트")
class SfMigrationStage2ServiceIntegrationTest {

    @PersistenceContext
    private lateinit var em: EntityManager

    private lateinit var service: SfMigrationStage2Service

    @BeforeEach
    @Transactional
    fun setUp() {
        service = SfMigrationStage2Service(em, BCryptPasswordEncoder())

        em.createNativeQuery("CREATE SCHEMA IF NOT EXISTS powersales").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.user_permission").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.sf_permission_set_assignment_raw").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.\"user\"").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.professional_promotion_team_master").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.employee").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.profile_flags").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.profile").executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.employee (
                employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_code VARCHAR(80),
                sfid VARCHAR(18),
                role VARCHAR(50),
                professional_promotion_team VARCHAR(80),
                cost_center_code VARCHAR(20)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales."user" (
                user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_code VARCHAR(80),
                sfid VARCHAR(18),
                password VARCHAR(255),
                password_change_required BOOLEAN DEFAULT FALSE,
                cost_center_code VARCHAR(20),
                profile_sfid VARCHAR(18),
                profile_id BIGINT
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.profile (
                profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sfid VARCHAR(18),
                name VARCHAR(255)
            )
            """.trimIndent()
        ).executeUpdate()
        // profile_flags — leader-profile-flags substep 대상. profile_id UNIQUE (운영 스키마 정합).
        em.createNativeQuery(
            """
            CREATE TABLE powersales.profile_flags (
                profile_flags_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                profile_id BIGINT UNIQUE,
                profile_name VARCHAR(255),
                permissions_view_all_data BOOLEAN DEFAULT FALSE NOT NULL,
                permissions_modify_all_data BOOLEAN DEFAULT FALSE NOT NULL,
                permissions_view_all_users BOOLEAN DEFAULT FALSE NOT NULL,
                permissions_manage_users BOOLEAN DEFAULT FALSE NOT NULL,
                permissions_api_enabled BOOLEAN DEFAULT FALSE NOT NULL,
                object_permissions VARCHAR(8000),
                custom_permissions VARCHAR(8000),
                is_locally_modified BOOLEAN DEFAULT FALSE NOT NULL
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.professional_promotion_team_master (
                professional_promotion_team_master_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_id BIGINT,
                branch_code VARCHAR(255)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.sf_permission_set_assignment_raw (
                assignee_employee_code VARCHAR(80),
                permission_set_name VARCHAR(80)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.user_permission (
                user_id BIGINT,
                permission VARCHAR(80),
                created_at TIMESTAMP,
                PRIMARY KEY (user_id, permission)
            )
            """.trimIndent()
        ).executeUpdate()
    }

    @Test
    @Transactional
    @DisplayName("Stage 2-B picklist — 한글 role 을 enum 으로 일괄 변환 + cost_center_code 동기화")
    fun runPicklistMapping() {
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, role, cost_center_code) VALUES ('E001', '여사원', '3233')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, role, cost_center_code) VALUES ('E002', '지점장', '4001')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, role) VALUES ('E003', '알수없는역할')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E001')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E002')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E003')").executeUpdate()

        val response = service.runPicklistMapping()

        assertThat(response.substep).isEqualTo("picklist")
        assertThat(response.totalRowsAffected).isGreaterThan(0)

        // spec #807 — Employee.role enum 변환 검증 폐기 (SF AppAuthority picklist value 가 곧 저장값).
        // Stage 1 적재 raw 값이 그대로 유지됨을 확인.
        assertThat(strOf("SELECT role FROM powersales.employee WHERE employee_code = 'E001'")).isEqualTo("여사원")
        assertThat(strOf("SELECT role FROM powersales.employee WHERE employee_code = 'E002'")).isEqualTo("지점장")
        assertThat(strOf("SELECT role FROM powersales.employee WHERE employee_code = 'E003'")).isEqualTo("알수없는역할")

        // Employee.cost_center_code → User.cost_center_code 동기화 검증
        assertThat(strOf("SELECT cost_center_code FROM powersales.\"user\" WHERE employee_code = 'E001'")).isEqualTo("3233")
        assertThat(strOf("SELECT cost_center_code FROM powersales.\"user\" WHERE employee_code = 'E002'")).isEqualTo("4001")
        assertThat(strOf("SELECT cost_center_code FROM powersales.\"user\" WHERE employee_code = 'E003'")).isNull()
    }

    // spec #807 — runPicklistEmployeeRole substep 폐기 (SF AppAuthority picklist value 가 곧 저장값).

    @Test
    @Transactional
    @DisplayName("Stage 2-B 개별 — runUserCostCenterCodeSync 만 호출 시 cost_center_code 만 동기화")
    fun runUserCostCenterCodeSync_only() {
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, cost_center_code) VALUES ('E001', '5001')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E001')").executeUpdate()

        val response = service.runUserCostCenterCodeSync()

        assertThat(response.substep).isEqualTo("picklist.user_cost_center_code")
        assertThat(strOf("SELECT cost_center_code FROM powersales.\"user\" WHERE employee_code = 'E001'")).isEqualTo("5001")
    }

    @Test
    @Transactional
    @DisplayName("Stage 2-B 개별 — runPptMasterBranchCodeSync: branch_code NULL row 만 사원 cost_center_code 로 채움 (멱등)")
    fun runPptMasterBranchCodeSync_only() {
        // E001(cc=3233), E002(cc=4001), E003(cc=NULL) 사원 + 마스터 3건 (사원별 1:1)
        em.createNativeQuery("INSERT INTO powersales.employee (employee_id, employee_code, cost_center_code) VALUES (1, 'E001', '3233')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.employee (employee_id, employee_code, cost_center_code) VALUES (2, 'E002', '4001')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.employee (employee_id, employee_code, cost_center_code) VALUES (3, 'E003', NULL)").executeUpdate()
        // M1(emp=1): branch_code NULL → 사원 cost_center_code 로 채워져야 함
        em.createNativeQuery("INSERT INTO powersales.professional_promotion_team_master (employee_id, branch_code) VALUES (1, NULL)").executeUpdate()
        // M2(emp=2): 이미 값 있음 → 보존 (멱등)
        em.createNativeQuery("INSERT INTO powersales.professional_promotion_team_master (employee_id, branch_code) VALUES (2, '9999')").executeUpdate()
        // M3(emp=3): 사원 cost_center_code 가 NULL → 건드리지 않음
        em.createNativeQuery("INSERT INTO powersales.professional_promotion_team_master (employee_id, branch_code) VALUES (3, NULL)").executeUpdate()

        val response = service.runPptMasterBranchCodeSync()

        assertThat(response.substep).isEqualTo("picklist.ppt_master_branch_code")
        // M1 채워짐 (emp=1 → 3233)
        assertThat(strOf("SELECT branch_code FROM powersales.professional_promotion_team_master WHERE employee_id = 1")).isEqualTo("3233")
        // M2 보존 (덮어쓰지 않음 — emp=2 의 4001 이 아닌 기존 9999 유지)
        assertThat(strOf("SELECT branch_code FROM powersales.professional_promotion_team_master WHERE employee_id = 2")).isEqualTo("9999")
        // M3 여전히 NULL (사원 cost_center_code NULL)
        assertThat(strOf("SELECT branch_code FROM powersales.professional_promotion_team_master WHERE employee_id = 3")).isNull()
        // 영향 행 = 1 (M1 만)
        assertThat(response.totalRowsAffected).isEqualTo(1)
    }

    @Test
    @Transactional
    @DisplayName("Stage 2-C password — sfid IS NOT NULL + password NULL 인 user 의 password 를 사번 기반 BCrypt 로 채움")
    fun runPasswordHash() {
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, sfid) VALUES ('E100', '005AAAAAA000001AAA')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, sfid, password) VALUES ('E101', '005AAAAAA000002AAA', '')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, sfid, password) VALUES ('E102', '005AAAAAA000003AAA', 'ALREADY-HASHED')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E103')").executeUpdate()

        val response = service.runPasswordHash()

        assertThat(response.substep).isEqualTo("password")
        assertThat(response.totalRowsAffected).isEqualTo(2)

        val pw100 = strOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E100'")
        val pw101 = strOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E101'")
        assertThat(pw100).startsWith("\$2a\$")
        assertThat(pw101).startsWith("\$2a\$")
        // 평문은 사번 기반 "{사번}@pwrs" — row 마다 다르다.
        assertThat(BCryptPasswordEncoder().matches("E100@pwrs", pw100)).isTrue()
        assertThat(BCryptPasswordEncoder().matches("E101@pwrs", pw101)).isTrue()
        // 다른 사번의 평문이나 사번 자체로는 매칭되지 않는다.
        assertThat(BCryptPasswordEncoder().matches("E101@pwrs", pw100)).isFalse()
        assertThat(BCryptPasswordEncoder().matches("E100", pw100)).isFalse()
        assertThat(pw100).isNotEqualTo(pw101)

        // password_change_required 강제 변경 플래그 설정 확인.
        assertThat(boolOf("SELECT password_change_required FROM powersales.\"user\" WHERE employee_code = 'E100'")).isTrue()

        assertThat(strOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E102'")).isEqualTo("ALREADY-HASHED")
        assertThat(objOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E103'")).isNull()

        // 멱등 — 재실행 시 변경 0.
        val again = service.runPasswordHash()
        assertThat(again.totalRowsAffected).isEqualTo(0)
    }

    @Test
    @Transactional
    @DisplayName("user profile reconcile — profile_sfid(SF 권위)로 profile_id override + 시스템 관리자 격상 보존 + 멱등")
    fun runUserProfileSfidReconcile() {
        // profile 4종 (진단 시나리오 정합): 5.영업사원 / 6.조장 / 9. Staff / 시스템 관리자
        em.createNativeQuery("INSERT INTO powersales.profile (profile_id, sfid, name) VALUES (24, '00e2x000000u01bAAA', '5.영업사원')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.profile (profile_id, sfid, name) VALUES (25, '00e2x000000u01cAAA', '6.조장')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.profile (profile_id, sfid, name) VALUES (9, '00e9x000000STAFAAA', '9. Staff')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.profile (profile_id, sfid, name) VALUES (1, '00e0x000000ADMIAAA', '시스템 관리자')").executeUpdate()

        // U1: SF=6.조장(sfid ...u01c) 인데 provisioning fallback 으로 5.영업사원(24) 선점 → 6.조장(25)로 교정 대상
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_sfid, profile_id) VALUES ('U1', '00e2x000000u01cAAA', 24)").executeUpdate()
        // U2: SF=6.조장 인데 9. Staff(9) 선점 → 6.조장(25)로 교정 대상
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_sfid, profile_id) VALUES ('U2', '00e2x000000u01cAAA', 9)").executeUpdate()
        // U3: 이미 SF정답(6.조장, 25)과 일치 → 멱등 (미대상)
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_sfid, profile_id) VALUES ('U3', '00e2x000000u01cAAA', 25)").executeUpdate()
        // U4: 현재 profile 이 '시스템 관리자'(1) 격상 계정 (SF정답은 9. Staff) → 보존 (되돌리지 않음)
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_sfid, profile_id) VALUES ('U4', '00e9x000000STAFAAA', 1)").executeUpdate()
        // U5: profile_sfid NULL (SF 마이그레이션 아님 — 신규 provisioning) → 미대상 (그대로 유지)
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_sfid, profile_id) VALUES ('U5', NULL, 24)").executeUpdate()
        // U6: profile_sfid 는 있으나 profile 테이블에 매칭 row 없음 → 미대상 (조인 실패, 그대로 유지)
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_sfid, profile_id) VALUES ('U6', '00eXXXXXXNOMATCAA', 24)").executeUpdate()

        val response = service.runUserProfileSfidReconcile()

        assertThat(response.substep).isEqualTo("userProfileSfidReconcile")
        // 교정 대상은 U1 + U2 만 (2건)
        assertThat(response.totalRowsAffected).isEqualTo(2)

        // U1, U2 → 6.조장(25)로 교정
        assertThat(longOf("SELECT profile_id FROM powersales.\"user\" WHERE employee_code = 'U1'")).isEqualTo(25L)
        assertThat(longOf("SELECT profile_id FROM powersales.\"user\" WHERE employee_code = 'U2'")).isEqualTo(25L)
        // U3 멱등 (이미 25)
        assertThat(longOf("SELECT profile_id FROM powersales.\"user\" WHERE employee_code = 'U3'")).isEqualTo(25L)
        // U4 시스템 관리자 격상 보존 (SF 9.Staff 로 되돌리지 않음 → 1 유지)
        assertThat(longOf("SELECT profile_id FROM powersales.\"user\" WHERE employee_code = 'U4'")).isEqualTo(1L)
        // U5 profile_sfid NULL → 미대상 (24 유지)
        assertThat(longOf("SELECT profile_id FROM powersales.\"user\" WHERE employee_code = 'U5'")).isEqualTo(24L)
        // U6 profile 매칭 없음 → 미대상 (24 유지)
        assertThat(longOf("SELECT profile_id FROM powersales.\"user\" WHERE employee_code = 'U6'")).isEqualTo(24L)

        // 멱등 — 재실행 시 변경 0
        val again = service.runUserProfileSfidReconcile()
        assertThat(again.totalRowsAffected).isEqualTo(0)
    }

    @Test
    @Transactional
    @DisplayName("user profile reconcile — SystemAdminGrantList 지정 사번은 SF(9.Staff) override 대신 시스템 관리자로 강제 격상 + 멱등")
    fun runUserProfileSfidReconcile_systemAdminGrantList() {
        // profile 2종: 9. Staff (SF 정답) / 시스템 관리자 (지정 격상 목표)
        em.createNativeQuery("INSERT INTO powersales.profile (profile_id, sfid, name) VALUES (9, '00e9x000000STAFAAA', '9. Staff')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.profile (profile_id, sfid, name) VALUES (1, '00e0x000000ADMIAAA', '시스템 관리자')").executeUpdate()

        // 지정 사번 (SystemAdminGrantList 실제 사번 2개 샘플) — SF profile_sfid 는 9. Staff.
        // reset 직후 시나리오: 현재 profile_id 를 SF 정답(9)으로 선점해 둔 상태 (아직 관리자 아님).
        val grantCode1 = "20000531" // 강현배
        val grantCode2 = "20210359" // 하헌준
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_sfid, profile_id) VALUES ('$grantCode1', '00e9x000000STAFAAA', 9)").executeUpdate()
        // 이미 관리자(1)로 격상돼 있는 지정 사번 → 멱등 (변화 없음)
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_sfid, profile_id) VALUES ('$grantCode2', '00e9x000000STAFAAA', 1)").executeUpdate()
        // 비지정 사번 (SF 9. Staff, 현재도 9) → SF override 대상이나 이미 일치라 무변화
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_sfid, profile_id) VALUES ('OTHER', '00e9x000000STAFAAA', 9)").executeUpdate()

        val response = service.runUserProfileSfidReconcile()

        assertThat(response.substep).isEqualTo("userProfileSfidReconcile")
        // grantCode1 만 9 → 1 (시스템 관리자) 로 격상. grantCode2 는 이미 1 (멱등). OTHER 는 override 대상이나 이미 9 라 무변화.
        assertThat(response.totalRowsAffected).isEqualTo(1)

        // 지정 사번 grantCode1 → 시스템 관리자(1) 로 강제 격상 (SF 9.Staff override 아님)
        assertThat(longOf("SELECT profile_id FROM powersales.\"user\" WHERE employee_code = '$grantCode1'")).isEqualTo(1L)
        // 지정 사번 grantCode2 → 이미 관리자 유지 (1)
        assertThat(longOf("SELECT profile_id FROM powersales.\"user\" WHERE employee_code = '$grantCode2'")).isEqualTo(1L)
        // 비지정 OTHER → SF 정답 9 유지 (격상 안 됨)
        assertThat(longOf("SELECT profile_id FROM powersales.\"user\" WHERE employee_code = 'OTHER'")).isEqualTo(9L)

        // 멱등 — 재실행 시 변경 0
        val again = service.runUserProfileSfidReconcile()
        assertThat(again.totalRowsAffected).isEqualTo(0)
    }

    // Stage 2-D permission substep 은 spec #801 SF 권한 모델 전면 적용으로 폐기됨.
    // user_permission 테이블 자체가 DROP (V186) 되어 본 테스트도 의미 상실.

    @Test
    @Transactional
    @DisplayName("Stage 2-A polymorphic parent — parent_type 별 record_sfid → parent_id Long FK 채움")
    fun runUploadFilePolymorphicParent() {
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.upload_file").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.claim").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.notice").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.suggestion").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.site_activity").executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.claim (
                claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sfid VARCHAR(18)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.notice (
                notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sfid VARCHAR(18)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.suggestion (
                suggestion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sfid VARCHAR(18)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.site_activity (
                site_activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sfid VARCHAR(18)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.upload_file (
                upload_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                object_type VARCHAR(40),
                parent_type VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
                parent_id BIGINT,
                record_sfid VARCHAR(40)
            )
            """.trimIndent()
        ).executeUpdate()

        em.createNativeQuery("INSERT INTO powersales.claim (claim_id, sfid) VALUES (100, 'a01CL000000001AAA')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.notice (notice_id, sfid) VALUES (200, 'a02NO000000001AAA')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.suggestion (suggestion_id, sfid) VALUES (300, 'a03SU000000001AAA')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.site_activity (site_activity_id, sfid) VALUES (400, 'a0D5A000000001AAA')").executeUpdate()

        // Stage1 적재 모사 — object_type (SF Object__c 원본) 만 채우고 parent_type 은 DEFAULT 'UNKNOWN'.
        em.createNativeQuery(
            "INSERT INTO powersales.upload_file (object_type, parent_id, record_sfid) VALUES ('DKRetail__Claim__c', NULL, 'a01CL000000001AAA')"
        ).executeUpdate()
        em.createNativeQuery(
            "INSERT INTO powersales.upload_file (object_type, parent_id, record_sfid) VALUES ('DKRetail__Notice__c', NULL, 'a02NO000000001AAA')"
        ).executeUpdate()
        em.createNativeQuery(
            "INSERT INTO powersales.upload_file (object_type, parent_id, record_sfid) VALUES ('DKRetail__Proposal__c', NULL, 'a03SU000000001AAA')"
        ).executeUpdate()
        em.createNativeQuery(
            "INSERT INTO powersales.upload_file (object_type, parent_id, record_sfid) VALUES ('DKRetail__SiteAcitivity__c', NULL, 'a0D5A000000001AAA')"
        ).executeUpdate()
        // 이미 parent_id 가 채워진 row — 멱등성 검증용 (parent_type 은 파생 대상이나 parent_id 유지).
        em.createNativeQuery(
            "INSERT INTO powersales.upload_file (object_type, parent_id, record_sfid) VALUES ('DKRetail__Claim__c', 999, 'a01CL000000001AAA')"
        ).executeUpdate()
        // record_sfid 가 어느 부모와도 매칭 안 되는 dangling row.
        em.createNativeQuery(
            "INSERT INTO powersales.upload_file (object_type, parent_id, record_sfid) VALUES ('DKRetail__Claim__c', NULL, 'a01XXXXXXXXXXXAAA')"
        ).executeUpdate()
        // object_type 이 빈 모바일 등록 경로 row (claim) — object_type 무관하게 record_sfid 로 연결되어야 함.
        em.createNativeQuery(
            "INSERT INTO powersales.upload_file (object_type, parent_id, record_sfid) VALUES (NULL, NULL, 'a01CL000000001AAA')"
        ).executeUpdate()

        val response = service.runUploadFilePolymorphicParent()

        assertThat(response.substep).isEqualTo("uploadFilePolymorphicParent")

        // record_sfid 직접 조인 — object_type 무관하게 부모 sfid 매칭으로 parent_type + parent_id 동시 설정.
        // claim 'a01CL...'(id=100) record_sfid 인 미연결 row 2건 (object_type='DKRetail__Claim__c' 1건 + NULL 1건).
        assertThat(longOf("SELECT COUNT(*) FROM powersales.upload_file WHERE record_sfid = 'a01CL000000001AAA' AND parent_type = 'Claim' AND parent_id = 100"))
            .isEqualTo(2L)
        // object_type 이 NULL 이어도 record_sfid 로 Claim 연결됨 (핵심 — 모바일 등록 경로 복원).
        assertThat(longOf("SELECT parent_id FROM powersales.upload_file WHERE object_type IS NULL"))
            .isEqualTo(100L)
        assertThat(longOf("SELECT COUNT(*) FROM powersales.upload_file WHERE object_type IS NULL AND parent_type = 'Claim'"))
            .isEqualTo(1L)

        // notice / suggestion / site_activity 도 record_sfid 조인으로 연결.
        assertThat(longOf("SELECT parent_id FROM powersales.upload_file WHERE record_sfid = 'a02NO000000001AAA' AND parent_type = 'Notice'"))
            .isEqualTo(200L)
        assertThat(longOf("SELECT parent_id FROM powersales.upload_file WHERE record_sfid = 'a03SU000000001AAA' AND parent_type = 'Suggestion'"))
            .isEqualTo(300L)
        assertThat(longOf("SELECT parent_id FROM powersales.upload_file WHERE record_sfid = 'a0D5A000000001AAA' AND parent_type = 'SiteActivity'"))
            .isEqualTo(400L)

        // 이미 parent_id=999 로 연결된 row 는 멱등 (parent_id IS NULL 조건이라 안 건드림).
        assertThat(longOf("SELECT parent_id FROM powersales.upload_file WHERE record_sfid = 'a01CL000000001AAA' AND parent_id = 999"))
            .isEqualTo(999L)
        // record_sfid 가 어느 부모와도 매칭 안 되는 dangling row → parent_id NULL 유지.
        assertThat(objOf("SELECT parent_id FROM powersales.upload_file WHERE record_sfid = 'a01XXXXXXXXXXXAAA'"))
            .isNull()
    }

    @Test
    @Transactional
    @DisplayName("notice rta placeholder — dry-run 은 본문 미변경 + 집계만, apply 는 placeholder 치환 + 멱등")
    fun runNoticeRtaPlaceholderRewrite() {
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.notice").executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.notice (
                notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                contents VARCHAR(4000),
                is_deleted BOOLEAN
            )
            """.trimIndent()
        ).executeUpdate()

        // (1) 본문에 rtaImage <img> 2개 (refid 있음 + alt 에 &amp; 포함) — 치환 대상.
        val rtaTag1 =
            """<img src="https://x.file.force.com/servlet/rtaImage?eid=a02&amp;feoid=00N&amp;refid=0EM001" alt="A&amp;B"/>"""
        val rtaTag2 =
            """<img src="https://x.file.force.com/servlet/rtaImage?eid=a02&amp;refid=0EM002">"""
        em.createNativeQuery("INSERT INTO powersales.notice (notice_id, contents, is_deleted) VALUES (10, :c, FALSE)")
            .setParameter("c", "<p>본문</p>$rtaTag1 중간 $rtaTag2 끝")
            .executeUpdate()

        // (2) rtaImage 지만 refid 없음 — 치환 불가 (skip 집계).
        em.createNativeQuery("INSERT INTO powersales.notice (notice_id, contents, is_deleted) VALUES (20, :c, FALSE)")
            .setParameter("c", """<img src="https://x.file.force.com/servlet/rtaImage?eid=a02">""")
            .executeUpdate()

        // (3) 이미 placeholder 치환된 본문 — 멱등 (변경 없음). LIKE '%rtaImage%' 에 안 걸려 조회조차 안 됨.
        em.createNativeQuery("INSERT INTO powersales.notice (notice_id, contents, is_deleted) VALUES (30, :c, FALSE)")
            .setParameter("c", """<img src="notice-image://0EM099" data-refid="0EM099">""")
            .executeUpdate()

        // (4) is_deleted=TRUE 인 공지 — 대상 제외.
        em.createNativeQuery("INSERT INTO powersales.notice (notice_id, contents, is_deleted) VALUES (40, :c, TRUE)")
            .setParameter("c", """<img src="https://x.file.force.com/servlet/rtaImage?refid=0EM040">""")
            .executeUpdate()

        // --- dry-run: 본문 미변경 + 집계 반환 ---
        val dry = service.runNoticeRtaPlaceholderRewrite(dryRun = true)
        assertThat(dry.substep).isEqualTo("noticeRtaPlaceholder (dry-run)")
        assertThat(dry.totalRowsAffected).isEqualTo(2) // 치환 이미지 수 (notice 10 의 2개)
        assertThat(labelRows(dry, "변경 대상 공지 수")).isEqualTo(1)
        assertThat(labelRows(dry, "refid 없는 rtaImage 태그")).isEqualTo(1)
        // dry-run 이라 본문은 원본 그대로 (rtaImage 잔존).
        assertThat(strOf("SELECT contents FROM powersales.notice WHERE notice_id = 10")).contains("rtaImage")

        // --- apply: 실제 placeholder 치환 ---
        val applied = service.runNoticeRtaPlaceholderRewrite(dryRun = false)
        assertThat(applied.substep).isEqualTo("noticeRtaPlaceholder")
        assertThat(applied.totalRowsAffected).isEqualTo(2)

        val c10 = strOf("SELECT contents FROM powersales.notice WHERE notice_id = 10")!!
        // 치환 결과 = placeholder 형태 (kts 와 동일). data-refid + notice-image:// + alt(&amp; 재이스케이프).
        assertThat(c10).contains("""<img src="notice-image://0EM001" data-refid="0EM001" alt="A&amp;B">""")
        assertThat(c10).contains("""<img src="notice-image://0EM002" data-refid="0EM002">""")
        assertThat(c10).doesNotContain("rtaImage")
        // refid 없는 notice 20 은 미변경.
        assertThat(strOf("SELECT contents FROM powersales.notice WHERE notice_id = 20")).contains("rtaImage")
        // is_deleted notice 40 은 미변경.
        assertThat(strOf("SELECT contents FROM powersales.notice WHERE notice_id = 40")).contains("rtaImage")

        // --- 멱등: 재실행 시 변경 0 (이미 치환된 본문은 정규식 미매칭으로 skip) ---
        val again = service.runNoticeRtaPlaceholderRewrite(dryRun = false)
        assertThat(again.totalRowsAffected).isEqualTo(0)
        assertThat(labelRows(again, "변경 대상 공지 수")).isEqualTo(0)
    }

    // ------------------------------------------------------------------
    // leader-profile-flags substep
    // ------------------------------------------------------------------

    /** '6.조장' profile + profile_flags row 를 준비한다. @param profileId 를 flags 에 연결(null 이면 미연결). */
    private fun seedLeaderProfile(
        profileId: Long = 10L,
        linkFlagsToProfile: Boolean = true,
        isLocallyModified: Boolean = false,
    ) {
        em.createNativeQuery(
            "INSERT INTO powersales.profile (profile_id, sfid, name) VALUES ($profileId, '00e000000000001', '6.조장')"
        ).executeUpdate()
        val fkValue = if (linkFlagsToProfile) "$profileId" else "NULL"
        em.createNativeQuery(
            """
            INSERT INTO powersales.profile_flags
                (profile_id, profile_name, permissions_api_enabled, is_locally_modified)
            VALUES ($fkValue, '6.조장', FALSE, $isLocallyModified)
            """.trimIndent()
        ).executeUpdate()
        em.flush()
        em.clear()
    }

    @Test
    @Transactional
    @DisplayName("leader-profile-flags — SoT 값으로 6.조장 flags 갱신 (api_enabled=true, object/custom 권한 적재)")
    fun `leader profile flags applies seed`() {
        seedLeaderProfile()

        val resp = service.runLeaderProfileFlags()

        assertThat(resp.substep).isEqualTo("leaderProfileFlags")
        assertThat(resp.totalRowsAffected).isEqualTo(1)
        assertThat(boolOf("SELECT permissions_api_enabled FROM powersales.profile_flags")).isTrue()
        // SoT 의 system 비트 — api_enabled 만 true, 나머지 false.
        assertThat(boolOf("SELECT permissions_view_all_data FROM powersales.profile_flags")).isFalse()
        assertThat(boolOf("SELECT permissions_modify_all_data FROM powersales.profile_flags")).isFalse()
        assertThat(strOf("SELECT object_permissions FROM powersales.profile_flags")).contains("Account")
    }

    @Test
    @Transactional
    @DisplayName("leader-profile-flags — 7.영업사원 + 조장 은 적용 대상 제외 (6.조장 단건 정책)")
    fun `leader profile flags targets only 6josang`() {
        seedLeaderProfile()
        // '7.영업사원 + 조장' 도 함께 존재시켜 대상에서 빠지는지 확인.
        em.createNativeQuery(
            "INSERT INTO powersales.profile (profile_id, sfid, name) VALUES (20, '00e000000000002', '7.영업사원 + 조장')"
        ).executeUpdate()
        em.createNativeQuery(
            """
            INSERT INTO powersales.profile_flags
                (profile_id, profile_name, permissions_api_enabled, is_locally_modified)
            VALUES (20, '7.영업사원 + 조장', FALSE, FALSE)
            """.trimIndent()
        ).executeUpdate()
        em.flush()
        em.clear()

        val resp = service.runLeaderProfileFlags()

        // 결과 라벨은 6.조장 1건만 — 7.영업사원 + 조장 은 아예 순회 대상에서 제외.
        assertThat(resp.results).hasSize(1)
        assertThat(resp.results[0].label).contains("6.조장")
        assertThat(
            boolOf("SELECT permissions_api_enabled FROM powersales.profile_flags WHERE profile_id = 20")
        ).isFalse()
    }

    @Test
    @Transactional
    @DisplayName("leader-profile-flags — is_locally_modified=TRUE 인 web admin 편집분은 skip")
    fun `leader profile flags skips dirty row`() {
        seedLeaderProfile(isLocallyModified = true)

        val resp = service.runLeaderProfileFlags()

        assertThat(resp.totalRowsAffected).isEqualTo(0)
        assertThat(resp.results[0].label).contains("web admin 편집분 보존")
        assertThat(boolOf("SELECT permissions_api_enabled FROM powersales.profile_flags")).isFalse()
    }

    @Test
    @Transactional
    @DisplayName("leader-profile-flags — profile_id 미연결(fk-natural-key 미실행) 시 create 하지 않고 skip")
    fun `leader profile flags skips when row not linked`() {
        seedLeaderProfile(linkFlagsToProfile = false)

        val resp = service.runLeaderProfileFlags()

        assertThat(resp.totalRowsAffected).isEqualTo(0)
        assertThat(resp.results[0].label).contains("row 부재")
        // 과거 부팅 Runner 의 UNIQUE 충돌 원인이던 create 분기가 없어야 한다 — row 수 불변.
        assertThat(longOf("SELECT COUNT(*) FROM powersales.profile_flags")).isEqualTo(1L)
    }

    @Test
    @Transactional
    @DisplayName("leader-profile-flags — 멱등 (2회 실행 시 두 번째는 0 row)")
    fun `leader profile flags is idempotent`() {
        seedLeaderProfile()

        assertThat(service.runLeaderProfileFlags().totalRowsAffected).isEqualTo(1)
        em.flush()
        em.clear()
        // H2/PG 모두 동일 값 UPDATE 는 row 를 다시 세지만, 값 자체가 SoT 와 일치해야 한다 (회귀 방지).
        service.runLeaderProfileFlags()
        assertThat(boolOf("SELECT permissions_api_enabled FROM powersales.profile_flags")).isTrue()
        assertThat(boolOf("SELECT is_locally_modified FROM powersales.profile_flags")).isFalse()
    }

    private fun labelRows(resp: com.otoki.powersales._migration.sf.dto.SfMigrationStage2Response, labelContains: String): Int =
        resp.results.first { it.label.contains(labelContains) }.rowsAffected

    private fun strOf(sql: String): String? = objOf(sql)?.toString()
    private fun longOf(sql: String): Long = (objOf(sql) as Number).toLong()
    private fun boolOf(sql: String): Boolean = objOf(sql) as Boolean
    private fun objOf(sql: String): Any? {
        val rows = em.createNativeQuery(sql).resultList
        return if (rows.isEmpty()) null else rows[0]
    }
}
