version: 0.2

env:
  variables:
    GRADLE_USER_HOME: "/root/.gradle"

phases:
  pre_build:
    commands:
      - echo "=== ECR Login ==="
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL
      - IMAGE_TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION:=latest}"
      - FULL_IMAGE="$ECR_REPOSITORY_URL:$IMAGE_TAG"
      - LATEST_IMAGE="$ECR_REPOSITORY_URL:latest"

  build:
    commands:
      - echo "=== Docker Build ==="
      - >
        docker build
        --cache-from $LATEST_IMAGE
        --build-arg BUILDKIT_INLINE_CACHE=1
        -t $FULL_IMAGE
        -t $LATEST_IMAGE
        -f backend/Dockerfile
        backend/

  post_build:
    commands:
      - echo "=== Push to ECR ==="
      - docker push $FULL_IMAGE
      - docker push $LATEST_IMAGE

      - echo "=== Update ECS Service ==="
      - >
        aws ecs update-service
        --cluster $ECS_CLUSTER_NAME
        --service $ECS_SERVICE_NAME
        --force-new-deployment
        --region $AWS_DEFAULT_REGION

      - echo "=== Deploy complete ==="

cache:
  paths:
    - "/root/.gradle/caches/**/*"
    - "/root/.gradle/wrapper/**/*"
