-- SALES_COMPARISON_READ 권한 시드.
-- 거래처별 진열사원 배치적합성 페이지 조회 권한.
-- 레거시 SF 의 UserRole 기반 분기 (ALL_BRANCHES: 영업지원실/영업본부장 등) 와 동등.
-- BRANCH_SCOPE (LEADER/BRANCH_MANAGER) 도 본인 지점 가시 범위 안에서 조회 가능.

INSERT INTO role_permission (role, permission)
VALUES
    ('SYSTEM_ADMIN', 'SALES_COMPARISON_READ'),
    ('LEADER', 'SALES_COMPARISON_READ'),
    ('BRANCH_MANAGER', 'SALES_COMPARISON_READ'),
    ('SALES_MANAGER', 'SALES_COMPARISON_READ'),
    ('BUSINESS_MANAGER', 'SALES_COMPARISON_READ'),
    ('HEADQUARTERS_MANAGER', 'SALES_COMPARISON_READ'),
    ('SALES_SUPPORT', 'SALES_COMPARISON_READ')
ON CONFLICT ON CONSTRAINT uq_role_permission DO NOTHING;
