-- 공지사항 FCM push 발송 이력.
-- web 관리자가 상세 화면의 '푸시 발송' 버튼으로 즉시 발송할 때마다 1행 기록한다.
-- 발송 결과(성공/실패 건수) 확인 + 중복 발송 경고(마지막 발송 시각/횟수)의 근거로 사용.
CREATE TABLE notice_push_log (
    notice_push_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id          BIGINT      NOT NULL,
    sent_by_id         BIGINT,
    target_scope       VARCHAR(255),
    target_count       INT         NOT NULL,
    success_count      INT         NOT NULL,
    failure_count      INT         NOT NULL,
    created_at         TIMESTAMP   NOT NULL,
    updated_at         TIMESTAMP   NOT NULL,
    CONSTRAINT fk_notice_push_log_notice FOREIGN KEY (notice_id) REFERENCES notice (notice_id)
);

CREATE INDEX idx_notice_push_log_notice_id ON notice_push_log (notice_id);
