-- 현장점검(결과) SiteActivity 엔티티 신규 — SF DKRetail__SiteAcitivity__c 마이그레이션 대상 추가.
--
-- 배경:
--   현장점검 등록(Theme__c → inspection_theme) 은 이미 마이그레이션 대상이나, 그 자식인
--   현장점검 결과(DKRetail__SiteAcitivity__c) 가 누락되어 있어 신규 적재 대상으로 추가.
--   SF 권위 출처: docs describe API dump (DKRetail__SiteAcitivity__c, 필드 33개).
--
-- 설계 정합 (inspection_theme V199/V200 누적 최종형을 신규 테이블에 일괄 반영):
--   - OwnerId.referenceTo = [Group, User] polymorphic →
--     owner_user_id (User FK) + owner_group_id (Group FK) + XOR CHECK
--   - CreatedById / LastModifiedById.referenceTo = [User] → audit FK 는 User
--   - *_sfid: Heroku Connect sync buffer (SF Id 보존). FK 미부착.
--   - *_id: SalesforceMigrationTool Stage2 fk substep 이 SF Id → 엔티티 FK 로 채움. ON DELETE SET NULL.
--   - lookup (Account / Employee / Product / Theme): *_sfid buffer + *_id FK 쌍.
--
-- Formula 필드 4개 (ThemeName__c / EmployeeOrgName__c / BranchName__c / OrgName__c) 는
--   calculated == true → backend-conventions §6.7 정책에 따라 DB 컬럼 미추가.

BEGIN;

CREATE TABLE powersales.site_activity (
    site_activity_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sfid                    VARCHAR(18) UNIQUE,
    name                    VARCHAR(80),

    -- 점검 본문
    activity_date           DATE,
    category                VARCHAR(255),       -- picklist: 본매대/행사매대/시식/기타
    product_type            VARCHAR(255),       -- picklist: 자사/경쟁사
    description             VARCHAR(4000),
    title                   VARCHAR(250),
    sap_account_code        VARCHAR(100),
    cost_center_code        VARCHAR(255),

    -- 경쟁사 활동
    competitor_name                     VARCHAR(100),
    competitor_product_name             VARCHAR(250),
    competitor_activity_description      VARCHAR(2000),
    competitor_proudct_price            NUMERIC(18, 0),  -- SF 원본 API 명 오타(Proudct) 유지
    sample_tast_flag                    VARCHAR(255),    -- picklist: Y/N
    sales_quantity                      NUMERIC(18, 0),

    is_deleted              BOOLEAN,

    -- lookup sync buffer (sfid) + 엔티티 FK
    account_sfid            VARCHAR(18),
    account_id              BIGINT,
    employee_sfid           VARCHAR(18),
    employee_id             BIGINT,
    product_sfid            VARCHAR(18),
    product_id              BIGINT,
    theme_sfid              VARCHAR(18),
    inspection_theme_id     BIGINT,

    -- owner (polymorphic) + audit
    owner_sfid              VARCHAR(18),
    owner_user_id           BIGINT,
    owner_group_id          BIGINT,
    created_by_sfid         VARCHAR(18),
    created_by_id           BIGINT,
    last_modified_by_sfid   VARCHAR(18),
    last_modified_by_id     BIGINT,

    -- BaseEntity audit
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_site_activity_account
        FOREIGN KEY (account_id) REFERENCES powersales.account (account_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_site_activity_employee
        FOREIGN KEY (employee_id) REFERENCES powersales.employee (employee_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_site_activity_product
        FOREIGN KEY (product_id) REFERENCES powersales.product (product_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_site_activity_inspection_theme
        FOREIGN KEY (inspection_theme_id) REFERENCES powersales.inspection_theme (inspection_theme_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_site_activity_owner_user
        FOREIGN KEY (owner_user_id) REFERENCES powersales."user" (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_site_activity_owner_group
        FOREIGN KEY (owner_group_id) REFERENCES powersales."group" (group_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_site_activity_created_by
        FOREIGN KEY (created_by_id) REFERENCES powersales."user" (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_site_activity_last_modified_by
        FOREIGN KEY (last_modified_by_id) REFERENCES powersales."user" (user_id)
        ON DELETE SET NULL,
    CONSTRAINT chk_site_activity_owner_xor
        CHECK (
            (owner_user_id IS NULL AND owner_group_id IS NULL)
            OR ((owner_user_id IS NOT NULL) <> (owner_group_id IS NOT NULL))
        )
);

-- FK 인덱스 (PostgreSQL 은 FK 제약 추가 시 자동 인덱스 생성 안 함)
CREATE INDEX idx_site_activity_account_id            ON powersales.site_activity (account_id);
CREATE INDEX idx_site_activity_employee_id           ON powersales.site_activity (employee_id);
CREATE INDEX idx_site_activity_product_id            ON powersales.site_activity (product_id);
CREATE INDEX idx_site_activity_inspection_theme_id   ON powersales.site_activity (inspection_theme_id);
CREATE INDEX idx_site_activity_owner_user_id         ON powersales.site_activity (owner_user_id);
CREATE INDEX idx_site_activity_owner_group_id        ON powersales.site_activity (owner_group_id);
CREATE INDEX idx_site_activity_created_by_id         ON powersales.site_activity (created_by_id);
CREATE INDEX idx_site_activity_last_modified_by_id   ON powersales.site_activity (last_modified_by_id);

COMMIT;
