-- 외부 HTTP outbound 호출 공통 관측 로그 (SAP / SF / Naver).
-- ExternalApiLogInterceptor 가 각 RestClient builder 에 등록되어 호출 1건당 1 row 적재.
CREATE TABLE external_api_log (
    external_api_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_system       VARCHAR(20)  NOT NULL,
    http_method         VARCHAR(10)  NOT NULL,
    uri                 VARCHAR(1000) NOT NULL,
    http_status         INTEGER,
    success             BOOLEAN      NOT NULL,
    duration_ms         BIGINT       NOT NULL,
    error_detail        TEXT,
    requested_at        TIMESTAMP    NOT NULL,
    completed_at        TIMESTAMP    NOT NULL
);

-- 시스템별 + 시간 역순 조회 (운영 트러블슈팅: 최근 실패 호출 추적).
CREATE INDEX idx_external_api_log_target_requested_at
    ON external_api_log (target_system, requested_at DESC);

-- 실패 호출만 빠르게 필터 (success = false).
CREATE INDEX idx_external_api_log_success_requested_at
    ON external_api_log (success, requested_at DESC);
