-- Spec #592
-- 범용 SAP outbound 송신 큐. 도메인 무관 (domain_type + aggregate_id + interface_id + payload poly 구조).
-- #598 (주문 취소) / #607 (claim 등록) 등 향후 SAP outbound 도메인이 동일 테이블 + 동일 워커 재사용.

CREATE TABLE powersales.sap_outbox (
    sap_outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_type VARCHAR(50) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    interface_id VARCHAR(80) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 워커 폴링용: WHERE status IN ('PENDING','RETRY') ORDER BY created_at
CREATE INDEX idx_sap_outbox_status_created_at
    ON powersales.sap_outbox (status, created_at);

-- 도메인 entity 별 outbox 조회용 (예: 주문 1건의 송신 이력)
CREATE INDEX idx_sap_outbox_domain_aggregate
    ON powersales.sap_outbox (domain_type, aggregate_id);
