-- V28: role_permission 정합성 복구 (Spec 외 hot fix).
--
-- 배경:
-- - V2 가 한글 라벨('시스템관리자' 등) 로 role_permission 을 시드했고
-- - V16 이 한글 → enum.name (SYSTEM_ADMIN 등) 으로 일괄 UPDATE.
-- - V19 가 V16 이후에 한글 라벨로 INSERT 하는 회귀 버그 (V16 컨텍스트 미반영).
-- - 운영 dev DB 의 role_permission row 가 외부 요인으로 비워진 상태에서 V19 만
--   적용되어, 현재 SYSTEM_ADMIN 권한이 0 건 → web admin 전 사용자 로그인 차단.
--
-- 조치:
-- 1) 한글 라벨 잔재 row 제거 (V19 misfire 정리).
-- 2) 8 운영 역할 × 기본 권한 매트릭스를 enum.name 으로 멱등 재시드 (ON CONFLICT DO NOTHING).
--
-- 이후 V19 의 한글 INSERT 는 별도 V29 등에서 enum.name 으로 교정할 수 있으나,
-- 본 V28 의 INSERT 가 SYSTEM_ADMIN/EMPLOYEE_RESET_CREDENTIALS 까지 포함하므로
-- 권한 매트릭스 자체는 본 마이그레이션으로 회복된다.

-- 1. 한글 라벨 row 정리
DELETE FROM role_permission
WHERE role NOT IN (
    'WOMAN', 'LEADER', 'BRANCH_MANAGER', 'SALES_MANAGER',
    'BUSINESS_MANAGER', 'HEADQUARTERS_MANAGER', 'SALES_SUPPORT', 'SYSTEM_ADMIN'
);

-- 2. enum.name 기반 권한 매트릭스 재시드 (idempotent)
INSERT INTO role_permission (role, permission) VALUES
    -- SYSTEM_ADMIN: 11 (10 base + EMPLOYEE_RESET_CREDENTIALS)
    ('SYSTEM_ADMIN', 'DASHBOARD_READ'),
    ('SYSTEM_ADMIN', 'EMPLOYEE_READ'),
    ('SYSTEM_ADMIN', 'EMPLOYEE_RESET_CREDENTIALS'),
    ('SYSTEM_ADMIN', 'ACCOUNT_READ'),
    ('SYSTEM_ADMIN', 'PROMOTION_READ'),
    ('SYSTEM_ADMIN', 'PROMOTION_WRITE'),
    ('SYSTEM_ADMIN', 'SAFETY_CHECK_READ'),
    ('SYSTEM_ADMIN', 'SCHEDULE_READ'),
    ('SYSTEM_ADMIN', 'SCHEDULE_WRITE'),
    ('SYSTEM_ADMIN', 'PRODUCT_EXPIRATION_READ'),
    ('SYSTEM_ADMIN', 'PRODUCT_EXPIRATION_WRITE'),

    -- LEADER (조장): 10
    ('LEADER', 'DASHBOARD_READ'),
    ('LEADER', 'EMPLOYEE_READ'),
    ('LEADER', 'ACCOUNT_READ'),
    ('LEADER', 'PROMOTION_READ'),
    ('LEADER', 'PROMOTION_WRITE'),
    ('LEADER', 'SAFETY_CHECK_READ'),
    ('LEADER', 'SCHEDULE_READ'),
    ('LEADER', 'SCHEDULE_WRITE'),
    ('LEADER', 'PRODUCT_EXPIRATION_READ'),
    ('LEADER', 'PRODUCT_EXPIRATION_WRITE'),

    -- BRANCH_MANAGER (지점장): 9 (SCHEDULE_WRITE 제외)
    ('BRANCH_MANAGER', 'DASHBOARD_READ'),
    ('BRANCH_MANAGER', 'EMPLOYEE_READ'),
    ('BRANCH_MANAGER', 'ACCOUNT_READ'),
    ('BRANCH_MANAGER', 'PROMOTION_READ'),
    ('BRANCH_MANAGER', 'PROMOTION_WRITE'),
    ('BRANCH_MANAGER', 'SAFETY_CHECK_READ'),
    ('BRANCH_MANAGER', 'SCHEDULE_READ'),
    ('BRANCH_MANAGER', 'PRODUCT_EXPIRATION_READ'),
    ('BRANCH_MANAGER', 'PRODUCT_EXPIRATION_WRITE'),

    -- SALES_MANAGER (영업부장): 9
    ('SALES_MANAGER', 'DASHBOARD_READ'),
    ('SALES_MANAGER', 'EMPLOYEE_READ'),
    ('SALES_MANAGER', 'ACCOUNT_READ'),
    ('SALES_MANAGER', 'PROMOTION_READ'),
    ('SALES_MANAGER', 'PROMOTION_WRITE'),
    ('SALES_MANAGER', 'SAFETY_CHECK_READ'),
    ('SALES_MANAGER', 'SCHEDULE_READ'),
    ('SALES_MANAGER', 'PRODUCT_EXPIRATION_READ'),
    ('SALES_MANAGER', 'PRODUCT_EXPIRATION_WRITE'),

    -- BUSINESS_MANAGER (사업부장): 9
    ('BUSINESS_MANAGER', 'DASHBOARD_READ'),
    ('BUSINESS_MANAGER', 'EMPLOYEE_READ'),
    ('BUSINESS_MANAGER', 'ACCOUNT_READ'),
    ('BUSINESS_MANAGER', 'PROMOTION_READ'),
    ('BUSINESS_MANAGER', 'PROMOTION_WRITE'),
    ('BUSINESS_MANAGER', 'SAFETY_CHECK_READ'),
    ('BUSINESS_MANAGER', 'SCHEDULE_READ'),
    ('BUSINESS_MANAGER', 'PRODUCT_EXPIRATION_READ'),
    ('BUSINESS_MANAGER', 'PRODUCT_EXPIRATION_WRITE'),

    -- HEADQUARTERS_MANAGER (영업본부장): 9
    ('HEADQUARTERS_MANAGER', 'DASHBOARD_READ'),
    ('HEADQUARTERS_MANAGER', 'EMPLOYEE_READ'),
    ('HEADQUARTERS_MANAGER', 'ACCOUNT_READ'),
    ('HEADQUARTERS_MANAGER', 'PROMOTION_READ'),
    ('HEADQUARTERS_MANAGER', 'PROMOTION_WRITE'),
    ('HEADQUARTERS_MANAGER', 'SAFETY_CHECK_READ'),
    ('HEADQUARTERS_MANAGER', 'SCHEDULE_READ'),
    ('HEADQUARTERS_MANAGER', 'PRODUCT_EXPIRATION_READ'),
    ('HEADQUARTERS_MANAGER', 'PRODUCT_EXPIRATION_WRITE'),

    -- SALES_SUPPORT (영업지원실): 10
    ('SALES_SUPPORT', 'DASHBOARD_READ'),
    ('SALES_SUPPORT', 'EMPLOYEE_READ'),
    ('SALES_SUPPORT', 'ACCOUNT_READ'),
    ('SALES_SUPPORT', 'PROMOTION_READ'),
    ('SALES_SUPPORT', 'PROMOTION_WRITE'),
    ('SALES_SUPPORT', 'SAFETY_CHECK_READ'),
    ('SALES_SUPPORT', 'SCHEDULE_READ'),
    ('SALES_SUPPORT', 'SCHEDULE_WRITE'),
    ('SALES_SUPPORT', 'PRODUCT_EXPIRATION_READ'),
    ('SALES_SUPPORT', 'PRODUCT_EXPIRATION_WRITE')
ON CONFLICT ON CONSTRAINT uq_role_permission DO NOTHING;
