-- education_post PK를 BIGINT IDENTITY로 변경 (기존 VARCHAR PK → edu_id 일반 컬럼)

-- 1. FK 제약조건 삭제 (PK 변경에 필요)
ALTER TABLE salesforce2.education_post DROP CONSTRAINT IF EXISTS fk_education_post_employee;

-- 2. 기존 PK 제약조건 삭제
ALTER TABLE salesforce2.education_post DROP CONSTRAINT education_post_pkey;

-- 3. 기존 PK 컬럼(education_post_id VARCHAR)을 edu_id로 변환
ALTER TABLE salesforce2.education_post RENAME COLUMN education_post_id TO edu_id;
ALTER TABLE salesforce2.education_post ALTER COLUMN edu_id DROP NOT NULL;

-- 4. 새 PK 컬럼 추가 (BIGINT IDENTITY)
ALTER TABLE salesforce2.education_post ADD COLUMN education_post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- 5. FK 제약조건 재생성
ALTER TABLE salesforce2.education_post ADD CONSTRAINT fk_education_post_employee
    FOREIGN KEY (employee_id) REFERENCES salesforce2.employee(employee_id);
