-- EducationViewHistory: 복합 PK → IDENTITY PK + FK 정규화
-- Spec #402

-- 1. 기존 복합 PK 제약조건 삭제
ALTER TABLE education_view_history DROP CONSTRAINT education_view_history_pkey;

-- 2. 신규 PK 컬럼 추가
ALTER TABLE education_view_history
    ADD COLUMN education_view_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- 3. education_post FK 컬럼 추가 + 데이터 변환
ALTER TABLE education_view_history ADD COLUMN education_post_id BIGINT;

UPDATE education_view_history evh
SET education_post_id = ep.education_post_id
FROM education_post ep
WHERE evh.community_id = ep.edu_id;

ALTER TABLE education_view_history ALTER COLUMN education_post_id SET NOT NULL;

-- 4. employee FK 컬럼 추가 + 데이터 변환
ALTER TABLE education_view_history ADD COLUMN employee_id BIGINT;

UPDATE education_view_history evh
SET employee_id = e.employee_id
FROM employee e
WHERE evh.emp_code = e.employee_code;

ALTER TABLE education_view_history ALTER COLUMN employee_id SET NOT NULL;

-- 5. inst_date → viewed_at 컬럼명 변경 + NOT NULL
ALTER TABLE education_view_history RENAME COLUMN inst_date TO viewed_at;
ALTER TABLE education_view_history ALTER COLUMN viewed_at SET NOT NULL;

-- 6. 레거시 컬럼 삭제
ALTER TABLE education_view_history DROP COLUMN community_id;
ALTER TABLE education_view_history DROP COLUMN emp_code;
ALTER TABLE education_view_history DROP COLUMN name;
ALTER TABLE education_view_history DROP COLUMN cost_center_code;

-- 7. FK 제약조건 추가
ALTER TABLE education_view_history
    ADD CONSTRAINT fk_education_view_history_post
        FOREIGN KEY (education_post_id) REFERENCES education_post(education_post_id);

ALTER TABLE education_view_history
    ADD CONSTRAINT fk_education_view_history_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id);

-- 8. 인덱스 생성
CREATE INDEX idx_education_view_history_post ON education_view_history(education_post_id);
CREATE INDEX idx_education_view_history_employee ON education_view_history(employee_id);
