-- LoginHistory: 복합 PK (employee_code, login_at) → surrogate PK (login_history_id) 전환
-- Spec #417

-- 1. 기존 복합 PK 제약조건 삭제
ALTER TABLE salesforce2.login_history DROP CONSTRAINT IF EXISTS employee_his_pkey;
ALTER TABLE salesforce2.login_history DROP CONSTRAINT IF EXISTS login_history_pkey;

-- 2. surrogate PK 컬럼 추가 + PRIMARY KEY 설정
ALTER TABLE salesforce2.login_history
    ADD COLUMN login_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- 3. NOT NULL 제약조건 확인 (이미 NOT NULL이면 무시)
ALTER TABLE salesforce2.login_history ALTER COLUMN employee_code SET NOT NULL;
ALTER TABLE salesforce2.login_history ALTER COLUMN login_at SET NOT NULL;
