-- AgreementHistory: GPS 동의 이력 테이블 (#136)
CREATE TABLE IF NOT EXISTS salesforce2.agreementhistory__c (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employeeid__c   BIGINT       NOT NULL REFERENCES salesforce2.dkretail__employee__c(id),
    agreementflag__c BOOLEAN     NOT NULL,
    agreementdate__c DATE        NOT NULL,
    agreementwordid__c BIGINT    NOT NULL REFERENCES salesforce2.agreementword__c(id),
    createddate     TIMESTAMP    NOT NULL DEFAULT now(),
    isdeleted       BOOLEAN      NOT NULL DEFAULT false
);

COMMENT ON TABLE salesforce2.agreementhistory__c IS 'GPS 동의 이력 (Salesforce AgreementHistory__c 대체)';
