CREATE TABLE organization (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cc_cd2     VARCHAR(10),
    org_cd2    VARCHAR(20),
    org_nm2    VARCHAR(100),
    cc_cd3     VARCHAR(10),
    org_cd3    VARCHAR(20),
    org_nm3    VARCHAR(100),
    cc_cd4     VARCHAR(10),
    org_cd4    VARCHAR(20),
    org_nm4    VARCHAR(100),
    cc_cd5     VARCHAR(10),
    org_cd5    VARCHAR(20),
    org_nm5    VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_organization_cc_cd3 ON organization (cc_cd3);
CREATE INDEX idx_organization_cc_cd4 ON organization (cc_cd4);
CREATE INDEX idx_organization_cc_cd5 ON organization (cc_cd5);
