-- StaffReview PK 및 레거시 컬럼명 정리 (#422)
ALTER TABLE staff_review RENAME COLUMN id TO staff_review_id;
ALTER TABLE staff_review RENAME COLUMN employeename__c TO employee_name;
ALTER TABLE staff_review RENAME COLUMN employeenumber__c TO employee_number;
ALTER TABLE staff_review RENAME COLUMN branch__c TO branch;
ALTER TABLE staff_review RENAME COLUMN branchreviews__c TO branch_reviews;
ALTER TABLE staff_review RENAME COLUMN costcentercode__c TO cost_center_code;
ALTER TABLE staff_review RENAME COLUMN employeetotalscore__c TO employee_total_score;
ALTER TABLE staff_review RENAME COLUMN attendance__c TO attendance;
ALTER TABLE staff_review RENAME COLUMN instructionsdefault__c TO instructions_default;
ALTER TABLE staff_review RENAME COLUMN priority_eventitemmanage__c TO priority_event_item_manage;
ALTER TABLE staff_review RENAME COLUMN displaymanageeventgoals__c TO display_manage_event_goals;
ALTER TABLE staff_review RENAME COLUMN businesspartnerties__c TO business_partner_ties;
ALTER TABLE staff_review RENAME COLUMN clothessatellite__c TO clothes_satellite;
ALTER TABLE staff_review RENAME COLUMN productmanagecallment__c TO product_manage_callment;
ALTER TABLE staff_review RENAME COLUMN educationalevaluation__c TO educational_evaluation;
ALTER TABLE staff_review RENAME COLUMN isdeleted TO is_deleted;
