CREATE TABLE salesforce2.account_category_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp
);

CREATE UNIQUE INDEX uq_account_category_master_code
    ON salesforce2.account_category_master (account_code);
