CREATE TABLE tmp_onsite (
    tmp_onsite_id       BIGSERIAL PRIMARY KEY,
    employee_code       VARCHAR(80),
    theme_code          VARCHAR(80),
    theme_name          VARCHAR(80),
    classification      VARCHAR(80),
    sap_account_name    VARCHAR(100),
    sap_account_code    VARCHAR(80),
    category            VARCHAR(100),
    activity_date       VARCHAR(80),
    description         TEXT,
    product_name        VARCHAR(80),
    product_code        VARCHAR(80),
    competitor_name     VARCHAR(80),
    competitor_activity TEXT,
    sample_tast_flag    VARCHAR(1),
    competitor_product_name VARCHAR(80),
    sample_taster_price VARCHAR(80),
    activity_amount     VARCHAR(40),
    s3_image_key1       VARCHAR(255),
    s3_image_key2       VARCHAR(255),
    s3_image_file_name1 VARCHAR(80),
    s3_image_file_size1 VARCHAR(80),
    s3_image_file_name2 VARCHAR(80),
    s3_image_file_size2 VARCHAR(80),
    account_id          BIGINT,
    employee_id         BIGINT,
    product_id          BIGINT,
    inspection_theme_id BIGINT,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP NOT NULL DEFAULT NOW()
);
