CREATE TABLE tmp_promotion (
    tmp_promotion_id       BIGSERIAL    PRIMARY KEY,
    employee_code          VARCHAR(80),
    promotion_type         VARCHAR(80),
    promotion_name         VARCHAR(100),
    promotion_product_name VARCHAR(80),
    promotion_product_code VARCHAR(80),
    base_price             VARCHAR(80),
    primary_quantity       VARCHAR(80),
    other_product          VARCHAR(80),
    other_quantity         VARCHAR(80),
    other_total_amount     VARCHAR(80),
    image_url              VARCHAR(200),
    heroku_promotion_id    VARCHAR(80),
    promotion_seq          VARCHAR(80),
    image_file_name        VARCHAR(80),
    other_change_product   VARCHAR(80),
    employee_id            BIGINT,
    product_id             BIGINT,
    created_at             TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMP    NOT NULL DEFAULT NOW()
);
