CREATE TABLE tmp_suggest (
    tmp_suggest_id      BIGSERIAL       PRIMARY KEY,
    category            VARCHAR(80),
    product_name        VARCHAR(80),
    product_code        VARCHAR(80),
    title               VARCHAR(100),
    description         TEXT,
    employee_code       VARCHAR(80),
    s3_image_url1       VARCHAR(80),
    s3_image_url2       VARCHAR(80),
    s3_image_file_name1 VARCHAR(80),
    s3_image_file_name2 VARCHAR(80),
    s3_image_file_size1 VARCHAR(80),
    s3_image_file_size2 VARCHAR(80),
    car_number          TEXT,
    account_code        TEXT,
    claim_list          TEXT,
    claim_date          DATE,
    employee_id         BIGINT,
    product_id          BIGINT,
    account_id          BIGINT,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);
