CREATE TABLE IF NOT EXISTS salesforce2.system_code_master (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code    varchar(10)  NOT NULL,
    group_code      varchar(20)  NOT NULL,
    detail_code     varchar(20)  NOT NULL,
    group_code_name varchar(100),
    detail_code_name varchar(100),
    seq             varchar(10),
    external_key    varchar(60)  NOT NULL,
    created_at      timestamp    NOT NULL DEFAULT now(),
    updated_at      timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_system_code_master_external_key
    ON salesforce2.system_code_master (external_key);

CREATE INDEX IF NOT EXISTS idx_system_code_master_group
    ON salesforce2.system_code_master (company_code, group_code);
