-- V7: Spec #142 - SAP 거래처/거래처분류 마스터 동기화
-- account 테이블 컬럼 추가 + account_category_master 테이블 신규 생성

-- 1. account 테이블 컬럼 추가
ALTER TABLE salesforce2.account
    ADD COLUMN IF NOT EXISTS account_type__c varchar(20),
    ADD COLUMN IF NOT EXISTS account_status_code__c varchar(20),
    ADD COLUMN IF NOT EXISTS account_status_name__c varchar(40),
    ADD COLUMN IF NOT EXISTS email__c varchar(255),
    ADD COLUMN IF NOT EXISTS business_type__c varchar(100),
    ADD COLUMN IF NOT EXISTS business_category__c varchar(100),
    ADD COLUMN IF NOT EXISTS employee_code__c varchar(20),
    ADD COLUMN IF NOT EXISTS business_license_number__c varchar(20),
    ADD COLUMN IF NOT EXISTS division_code__c varchar(20),
    ADD COLUMN IF NOT EXISTS division_name__c varchar(100),
    ADD COLUMN IF NOT EXISTS sales_dept_code__c varchar(20),
    ADD COLUMN IF NOT EXISTS sales_dept_name__c varchar(100),
    ADD COLUMN IF NOT EXISTS distribution__c varchar(1),
    ADD COLUMN IF NOT EXISTS consignment_acc__c varchar(1),
    ADD COLUMN IF NOT EXISTS werk1__c varchar(10),
    ADD COLUMN IF NOT EXISTS werk2__c varchar(10),
    ADD COLUMN IF NOT EXISTS werk3__c varchar(10),
    ADD COLUMN IF NOT EXISTS org_cd3__c varchar(20),
    ADD COLUMN IF NOT EXISTS org_cd4__c varchar(20),
    ADD COLUMN IF NOT EXISTS org_cd5__c varchar(20),
    ADD COLUMN IF NOT EXISTS created_at timestamp,
    ADD COLUMN IF NOT EXISTS updated_at timestamp;

-- 2. account externalkey__c UNIQUE 인덱스
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_externalkey
    ON salesforce2.account (externalkey__c);

-- 3. account_category_master 테이블 신규 생성
CREATE TABLE salesforce2.account_category_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp
);

CREATE UNIQUE INDEX uq_account_category_master_code
    ON salesforce2.account_category_master (account_code);
