CREATE TABLE daily_sales_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sap_account_code VARCHAR(20)      NOT NULL,
    sales_date       VARCHAR(8)       NOT NULL,
    external_key     VARCHAR(30)      NOT NULL,
    erp_sales_amount1        DOUBLE PRECISION,
    erp_sales_amount2        DOUBLE PRECISION,
    erp_sales_amount3        DOUBLE PRECISION,
    erp_distribution_amount1 DOUBLE PRECISION,
    erp_distribution_amount2 DOUBLE PRECISION,
    erp_distribution_amount3 DOUBLE PRECISION,
    ledger_amount            DOUBLE PRECISION,
    created_at       TIMESTAMP        NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP
);

CREATE UNIQUE INDEX uq_daily_sales_external_key ON daily_sales_history (external_key);
CREATE INDEX idx_daily_sales_account ON daily_sales_history (sap_account_code);
CREATE INDEX idx_daily_sales_date ON daily_sales_history (sales_date);
