-- 스펙 #548: 스케줄 잡 실행 이력 테이블.
--
-- ScheduledJobRunner 가 잡 본문 진입/종료 시점에 row 를 INSERT/UPDATE 하여
-- 운영 SQL 만으로 잡 실행 결과(성공/실패/실행시간/메타데이터)를 추적할 수 있게 한다.
-- ShedLock 락 획득 후 잡 본문 안쪽에서 호출되며, INSERT 와 종료 UPDATE 는 각각
-- REQUIRES_NEW 트랜잭션으로 분리되어 본문 람다의 트랜잭션 롤백과 무관하게 영속된다.
-- 시각 타입은 #550 에서 도입할 전사 정책(TIMESTAMPTZ + Instant) 을 선제 적용한다.
-- 보존 기간 90일 — ScheduledJobRunCleanupJob 이 매일 04:00 cleanup 한다.

CREATE TABLE powersales.scheduled_job_run (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name      VARCHAR(64)                  NOT NULL,
    started_at    TIMESTAMP(3) WITH TIME ZONE  NOT NULL,
    ended_at      TIMESTAMP(3) WITH TIME ZONE,
    status        VARCHAR(16)                  NOT NULL,
    error_message VARCHAR(4000),
    metadata      JSONB,
    created_at    TIMESTAMP(3) WITH TIME ZONE  NOT NULL
);

-- "최근 N건 조회" — 잡별 시간 역순 페이징 쿼리 최적화.
CREATE INDEX idx_scheduled_job_run_job_started
    ON powersales.scheduled_job_run (job_name, started_at DESC);

-- "최근 실패 잡 조회" — status = 'FAILURE' AND started_at > now() - INTERVAL ... 쿼리 최적화.
CREATE INDEX idx_scheduled_job_run_status_started
    ON powersales.scheduled_job_run (status, started_at DESC);
