-- Spec #144: SAP 매출 데이터 동기화

-- 1. daily_sales_history 테이블 신규 생성
CREATE TABLE daily_sales_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sap_account_code VARCHAR(20)      NOT NULL,
    sales_date       VARCHAR(8)       NOT NULL,
    external_key     VARCHAR(30)      NOT NULL,
    erp_sales_amount1        DOUBLE PRECISION,
    erp_sales_amount2        DOUBLE PRECISION,
    erp_sales_amount3        DOUBLE PRECISION,
    erp_distribution_amount1 DOUBLE PRECISION,
    erp_distribution_amount2 DOUBLE PRECISION,
    erp_distribution_amount3 DOUBLE PRECISION,
    ledger_amount            DOUBLE PRECISION,
    created_at       TIMESTAMP        NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP
);

CREATE UNIQUE INDEX uq_daily_sales_external_key ON daily_sales_history (external_key);
CREATE INDEX idx_daily_sales_account ON daily_sales_history (sap_account_code);
CREATE INDEX idx_daily_sales_date ON daily_sales_history (sales_date);

-- 2. monthlysaleshistory__c 테이블에 컬럼 추가
ALTER TABLE monthlysaleshistory__c ADD COLUMN IF NOT EXISTS externalkey__c VARCHAR(30);
ALTER TABLE monthlysaleshistory__c ADD COLUMN IF NOT EXISTS rlsales__c DOUBLE PRECISION;

CREATE UNIQUE INDEX uq_monthly_sales_externalkey ON monthlysaleshistory__c (externalkey__c);
