###############################################################################
# Elastic Beanstalk — backend (Docker on Amazon Linux 2023)
#
# Application:  dev-otk-pwrs-backend
# Environment:  dev-otk-pwrs-backend-env
#
# NOTE: EB option_settings include many AWS-computed defaults returned by the
# API. To keep `terraform plan` at diff 0 after import we declare the key
# user-configured settings and use `ignore_changes = [setting]` so Terraform
# does not fight the provider over computed/default values. To manage a
# specific option via Terraform, remove that element from ignore_changes and
# ensure its setting{} block is present.
###############################################################################

resource "aws_elastic_beanstalk_application" "backend" {
  name = "${local.name_prefix}-backend"
}

resource "aws_elastic_beanstalk_environment" "backend" {
  name                = "${local.name_prefix}-backend-env"
  application         = aws_elastic_beanstalk_application.backend.name
  platform_arn        = "arn:aws:elasticbeanstalk:ap-northeast-2::platform/Docker running on 64bit Amazon Linux 2023/4.12.1"
  tier                = "WebServer"
  wait_for_ready_timeout = "20m"

  # --- VPC / subnets -------------------------------------------------------
  setting {
    namespace = "aws:ec2:vpc"
    name      = "VPCId"
    value     = aws_vpc.main.id
  }
  setting {
    namespace = "aws:ec2:vpc"
    name      = "Subnets"
    value     = join(",", [aws_subnet.app_a.id, aws_subnet.app_c.id])
  }
  setting {
    namespace = "aws:ec2:vpc"
    name      = "ELBSubnets"
    value     = join(",", [aws_subnet.public_a.id, aws_subnet.public_c.id])
  }
  setting {
    namespace = "aws:ec2:vpc"
    name      = "ELBScheme"
    value     = "public"
  }
  setting {
    namespace = "aws:ec2:vpc"
    name      = "AssociatePublicIpAddress"
    value     = "false"
  }

  # --- Launch configuration / EC2 -----------------------------------------
  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "IamInstanceProfile"
    value     = aws_iam_instance_profile.eb_ec2.name
  }
  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "InstanceType"
    value     = "t3.small"
  }
  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "DisableIMDSv1"
    value     = "true"
  }
  # NOTE: second SG (sg-08e9dbd463207f4d7) is EB-autogenerated — not managed here.
  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "SecurityGroups"
    value     = aws_security_group.eb.id
  }

  # --- Auto Scaling --------------------------------------------------------
  setting {
    namespace = "aws:autoscaling:asg"
    name      = "MinSize"
    value     = "1"
  }
  setting {
    namespace = "aws:autoscaling:asg"
    name      = "MaxSize"
    value     = "4"
  }

  # --- Environment type / ALB ---------------------------------------------
  setting {
    namespace = "aws:elasticbeanstalk:environment"
    name      = "EnvironmentType"
    value     = "LoadBalanced"
  }
  setting {
    namespace = "aws:elasticbeanstalk:environment"
    name      = "LoadBalancerType"
    value     = "application"
  }
  setting {
    namespace = "aws:elasticbeanstalk:environment"
    name      = "ServiceRole"
    value     = data.aws_iam_role.eb_service.arn
  }

  # --- Health check --------------------------------------------------------
  setting {
    namespace = "aws:elasticbeanstalk:environment:process:default"
    name      = "HealthCheckPath"
    value     = "/actuator/health"
  }
  setting {
    namespace = "aws:elasticbeanstalk:environment:process:default"
    name      = "HealthCheckInterval"
    value     = "15"
  }
  setting {
    namespace = "aws:elasticbeanstalk:environment:process:default"
    name      = "HealthyThresholdCount"
    value     = "3"
  }
  setting {
    namespace = "aws:elasticbeanstalk:environment:process:default"
    name      = "UnhealthyThresholdCount"
    value     = "5"
  }

  # --- HTTPS listener ------------------------------------------------------
  setting {
    namespace = "aws:elbv2:listener:443"
    name      = "ListenerEnabled"
    value     = "true"
  }
  setting {
    namespace = "aws:elbv2:listener:443"
    name      = "Protocol"
    value     = "HTTPS"
  }
  setting {
    namespace = "aws:elbv2:listener:443"
    name      = "SSLCertificateArns"
    value     = aws_acm_certificate.api_dev.arn
  }

  # --- Enhanced health ------------------------------------------------------
  setting {
    namespace = "aws:elasticbeanstalk:healthreporting:system"
    name      = "SystemType"
    value     = "enhanced"
  }

  # --- Managed platform updates --------------------------------------------
  setting {
    namespace = "aws:elasticbeanstalk:managedactions"
    name      = "ManagedActionsEnabled"
    value     = "true"
  }
  setting {
    namespace = "aws:elasticbeanstalk:managedactions"
    name      = "PreferredStartTime"
    value     = "SUN:01:10"
  }
  setting {
    namespace = "aws:elasticbeanstalk:managedactions"
    name      = "ServiceRoleForManagedUpdates"
    value     = data.aws_iam_role.eb_service.arn
  }
  setting {
    namespace = "aws:elasticbeanstalk:managedactions:platformupdate"
    name      = "UpdateLevel"
    value     = "minor"
  }

  lifecycle {
    ignore_changes = [
      setting,
      platform_arn,
      version_label,
    ]
  }
}
