package com.otoki.powersales.sfmigration.service

import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import com.otoki.powersales.common.config.QueryDslConfig
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase
import org.springframework.context.annotation.Import
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.context.TestPropertySource
import org.springframework.transaction.annotation.Transactional

/**
 * Stage 2 Service 통합 테스트 — H2 PostgreSQL 호환 모드 + native query 동작 검증.
 *
 * `@DataJpaTest` 슬라이스 + H2 url 을 PostgreSQL 호환 모드로 override.
 * powersales schema + 4개 minimal 테이블을 BeforeEach 로 직접 생성한다 (Flyway 미사용).
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
@Import(QueryDslConfig::class)
@TestPropertySource(
    properties = [
        "spring.datasource.url=jdbc:h2:mem:sfmigration_stage2_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false",
    ],
)
@DisplayName("SfMigrationStage2Service 통합 테스트")
class SfMigrationStage2ServiceIntegrationTest {

    @PersistenceContext
    private lateinit var em: EntityManager

    private lateinit var service: SfMigrationStage2Service

    @BeforeEach
    @Transactional
    fun setUp() {
        service = SfMigrationStage2Service(em, BCryptPasswordEncoder())

        em.createNativeQuery("CREATE SCHEMA IF NOT EXISTS powersales").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.user_permission").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.sf_permission_set_assignment_raw").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.\"user\"").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.employee").executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.employee (
                employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_code VARCHAR(80),
                sfid VARCHAR(18),
                role VARCHAR(50),
                professional_promotion_team VARCHAR(80),
                cost_center_code VARCHAR(20)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales."user" (
                user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_code VARCHAR(80),
                sfid VARCHAR(18),
                password VARCHAR(255),
                password_change_required BOOLEAN DEFAULT FALSE,
                cost_center_code VARCHAR(20)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.sf_permission_set_assignment_raw (
                assignee_employee_code VARCHAR(80),
                permission_set_name VARCHAR(80)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.user_permission (
                user_id BIGINT,
                permission VARCHAR(80),
                created_at TIMESTAMP,
                PRIMARY KEY (user_id, permission)
            )
            """.trimIndent()
        ).executeUpdate()
    }

    @Test
    @Transactional
    @DisplayName("Stage 2-B picklist — 한글 role 을 enum 으로 일괄 변환 + cost_center_code 동기화")
    fun runPicklistMapping() {
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, role, cost_center_code) VALUES ('E001', '여사원', '3233')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, role, cost_center_code) VALUES ('E002', '지점장', '4001')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, role) VALUES ('E003', '알수없는역할')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E001')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E002')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E003')").executeUpdate()

        val response = service.runPicklistMapping()

        assertThat(response.substep).isEqualTo("picklist")
        assertThat(response.totalRowsAffected).isGreaterThan(0)

        assertThat(strOf("SELECT role FROM powersales.employee WHERE employee_code = 'E001'")).isEqualTo("WOMAN")
        assertThat(strOf("SELECT role FROM powersales.employee WHERE employee_code = 'E002'")).isEqualTo("BRANCH_MANAGER")
        assertThat(strOf("SELECT role FROM powersales.employee WHERE employee_code = 'E003'")).isEqualTo("UNKNOWN")

        // Employee.cost_center_code → User.cost_center_code 동기화 검증
        assertThat(strOf("SELECT cost_center_code FROM powersales.\"user\" WHERE employee_code = 'E001'")).isEqualTo("3233")
        assertThat(strOf("SELECT cost_center_code FROM powersales.\"user\" WHERE employee_code = 'E002'")).isEqualTo("4001")
        assertThat(strOf("SELECT cost_center_code FROM powersales.\"user\" WHERE employee_code = 'E003'")).isNull()
    }

    @Test
    @Transactional
    @DisplayName("Stage 2-B 개별 — runPicklistEmployeeRole 만 호출 시 role 만 변환")
    fun runPicklistEmployeeRole_only() {
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, role) VALUES ('E001', '여사원')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E001')").executeUpdate()

        val response = service.runPicklistEmployeeRole()

        assertThat(response.substep).isEqualTo("picklist.employee_role")
        assertThat(strOf("SELECT role FROM powersales.employee WHERE employee_code = 'E001'")).isEqualTo("WOMAN")
    }

    @Test
    @Transactional
    @DisplayName("Stage 2-B 개별 — runUserCostCenterCodeSync 만 호출 시 cost_center_code 만 동기화")
    fun runUserCostCenterCodeSync_only() {
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, cost_center_code) VALUES ('E001', '5001')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E001')").executeUpdate()

        val response = service.runUserCostCenterCodeSync()

        assertThat(response.substep).isEqualTo("picklist.user_cost_center_code")
        assertThat(strOf("SELECT cost_center_code FROM powersales.\"user\" WHERE employee_code = 'E001'")).isEqualTo("5001")
    }

    @Test
    @Transactional
    @DisplayName("Stage 2-C password — sfid IS NOT NULL + password NULL 인 user 의 password 를 BCrypt 로 채움")
    fun runPasswordHash() {
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, sfid) VALUES ('E100', '005AAAAAA000001AAA')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, sfid, password) VALUES ('E101', '005AAAAAA000002AAA', '')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, sfid, password) VALUES ('E102', '005AAAAAA000003AAA', 'ALREADY-HASHED')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E103')").executeUpdate()

        val response = service.runPasswordHash()

        assertThat(response.substep).isEqualTo("password")
        assertThat(response.totalRowsAffected).isEqualTo(2)

        val pw100 = strOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E100'")
        val pw101 = strOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E101'")
        assertThat(pw100).startsWith("\$2a\$")
        assertThat(pw101).startsWith("\$2a\$")
        assertThat(BCryptPasswordEncoder().matches("E100", pw100)).isTrue()
        assertThat(BCryptPasswordEncoder().matches("E101", pw101)).isTrue()

        assertThat(strOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E102'")).isEqualTo("ALREADY-HASHED")
        assertThat(objOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E103'")).isNull()
    }

    // Stage 2-D permission substep 은 spec #801 SF 권한 모델 전면 적용으로 폐기됨.
    // user_permission 테이블 자체가 DROP (V186) 되어 본 테스트도 의미 상실.

    private fun strOf(sql: String): String? = objOf(sql)?.toString()
    private fun longOf(sql: String): Long = (objOf(sql) as Number).toLong()
    private fun objOf(sql: String): Any? {
        val rows = em.createNativeQuery(sql).resultList
        return if (rows.isEmpty()) null else rows[0]
    }
}
