package com.otoki.powersales.sfmigration.service

import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import com.otoki.powersales.common.config.QueryDslConfig
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase
import org.springframework.context.annotation.Import
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.context.TestPropertySource
import org.springframework.transaction.annotation.Transactional

/**
 * Stage 2 Service 통합 테스트 — H2 PostgreSQL 호환 모드 + native query 동작 검증.
 *
 * `@DataJpaTest` 슬라이스 + H2 url 을 PostgreSQL 호환 모드로 override.
 * powersales schema + 4개 minimal 테이블을 BeforeEach 로 직접 생성한다 (Flyway 미사용).
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
@Import(QueryDslConfig::class)
@TestPropertySource(
    properties = [
        "spring.datasource.url=jdbc:h2:mem:sfmigration_stage2_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false",
    ],
)
@DisplayName("SfMigrationStage2Service 통합 테스트")
class SfMigrationStage2ServiceIntegrationTest {

    @PersistenceContext
    private lateinit var em: EntityManager

    private lateinit var service: SfMigrationStage2Service

    @BeforeEach
    @Transactional
    fun setUp() {
        service = SfMigrationStage2Service(em, BCryptPasswordEncoder())

        em.createNativeQuery("CREATE SCHEMA IF NOT EXISTS powersales").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.user_permission").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.sf_permission_set_assignment_raw").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.\"user\"").executeUpdate()
        em.createNativeQuery("DROP TABLE IF EXISTS powersales.employee").executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.employee (
                employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_code VARCHAR(80),
                sfid VARCHAR(18),
                role VARCHAR(50),
                professional_promotion_team VARCHAR(80)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales."user" (
                user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_code VARCHAR(80),
                sfid VARCHAR(18),
                profile_type VARCHAR(50),
                password VARCHAR(255),
                password_change_required BOOLEAN DEFAULT FALSE
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.sf_permission_set_assignment_raw (
                assignee_employee_code VARCHAR(80),
                permission_set_name VARCHAR(80)
            )
            """.trimIndent()
        ).executeUpdate()
        em.createNativeQuery(
            """
            CREATE TABLE powersales.user_permission (
                user_id BIGINT,
                permission VARCHAR(80),
                created_at TIMESTAMP,
                PRIMARY KEY (user_id, permission)
            )
            """.trimIndent()
        ).executeUpdate()
    }

    @Test
    @Transactional
    @DisplayName("Stage 2-B picklist — 한글 role/ppt/profile_type 을 enum 으로 일괄 변환")
    fun runPicklistMapping() {
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, role, professional_promotion_team) VALUES ('E001', '여사원', '라면세일조')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, role, professional_promotion_team) VALUES ('E002', '지점장', '프레시세일조_냉장')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.employee (employee_code, role) VALUES ('E003', '알수없는역할')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_type) VALUES ('E001', '8. 마케팅')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_type) VALUES ('E002', '4. 지점장')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, profile_type) VALUES ('E003', '알수없는프로필')").executeUpdate()

        val response = service.runPicklistMapping()

        assertThat(response.substep).isEqualTo("picklist")
        assertThat(response.totalRowsAffected).isGreaterThan(0)

        assertThat(strOf("SELECT role FROM powersales.employee WHERE employee_code = 'E001'")).isEqualTo("WOMAN")
        assertThat(strOf("SELECT role FROM powersales.employee WHERE employee_code = 'E002'")).isEqualTo("BRANCH_MANAGER")
        assertThat(strOf("SELECT role FROM powersales.employee WHERE employee_code = 'E003'")).isEqualTo("UNKNOWN")

        assertThat(strOf("SELECT professional_promotion_team FROM powersales.employee WHERE employee_code = 'E001'")).isEqualTo("RAMEN_SALE")
        assertThat(strOf("SELECT professional_promotion_team FROM powersales.employee WHERE employee_code = 'E002'")).isEqualTo("FRESH_SALE_REFRIGERATED")

        assertThat(strOf("SELECT profile_type FROM powersales.\"user\" WHERE employee_code = 'E001'")).isEqualTo("MARKETING")
        assertThat(strOf("SELECT profile_type FROM powersales.\"user\" WHERE employee_code = 'E002'")).isEqualTo("BRANCH_MANAGER")
        assertThat(strOf("SELECT profile_type FROM powersales.\"user\" WHERE employee_code = 'E003'")).isEqualTo("STAFF")
    }

    @Test
    @Transactional
    @DisplayName("Stage 2-C password — sfid IS NOT NULL + password NULL 인 user 의 password 를 BCrypt 로 채움")
    fun runPasswordHash() {
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, sfid) VALUES ('E100', '005AAAAAA000001AAA')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, sfid, password) VALUES ('E101', '005AAAAAA000002AAA', '')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code, sfid, password) VALUES ('E102', '005AAAAAA000003AAA', 'ALREADY-HASHED')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (employee_code) VALUES ('E103')").executeUpdate()

        val response = service.runPasswordHash()

        assertThat(response.substep).isEqualTo("password")
        assertThat(response.totalRowsAffected).isEqualTo(2)

        val pw100 = strOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E100'")
        val pw101 = strOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E101'")
        assertThat(pw100).startsWith("\$2a\$")
        assertThat(pw101).startsWith("\$2a\$")
        assertThat(BCryptPasswordEncoder().matches("E100", pw100)).isTrue()
        assertThat(BCryptPasswordEncoder().matches("E101", pw101)).isTrue()

        assertThat(strOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E102'")).isEqualTo("ALREADY-HASHED")
        assertThat(objOf("SELECT password FROM powersales.\"user\" WHERE employee_code = 'E103'")).isNull()
    }

    @Test
    @Transactional
    @DisplayName("Stage 2-D permission — sf_permission_set_assignment_raw JOIN user → user_permission INSERT")
    fun runPermissionMapping() {
        em.createNativeQuery("INSERT INTO powersales.\"user\" (user_id, employee_code) VALUES (10, 'E200')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.\"user\" (user_id, employee_code) VALUES (11, 'E201')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.sf_permission_set_assignment_raw VALUES ('E200', 'Employee_View_All')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.sf_permission_set_assignment_raw VALUES ('E200', 'SalesSupport')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.sf_permission_set_assignment_raw VALUES ('E201', 'Object_View_All')").executeUpdate()
        em.createNativeQuery("INSERT INTO powersales.sf_permission_set_assignment_raw VALUES ('E201', 'MFA')").executeUpdate()

        val response = service.runPermissionMapping()

        assertThat(response.substep).isEqualTo("permission")
        assertThat(response.totalRowsAffected).isGreaterThan(0)

        val e200Perms = longOf("SELECT COUNT(*) FROM powersales.user_permission WHERE user_id = 10")
        val e201Perms = longOf("SELECT COUNT(*) FROM powersales.user_permission WHERE user_id = 11")
        // Employee_View_All=EMPLOYEE_READ + SalesSupport=DASHBOARD_READ/EMPLOYEE_READ(중복 ON CONFLICT)/ACCOUNT_READ/SCHEDULE_READ
        // → unique 4 (EMPLOYEE_READ, DASHBOARD_READ, ACCOUNT_READ, SCHEDULE_READ)
        assertThat(e200Perms).isEqualTo(4L)
        // Object_View_All=ACCOUNT_READ + EMPLOYEE_READ, MFA=skip
        assertThat(e201Perms).isEqualTo(2L)
    }

    private fun strOf(sql: String): String? = objOf(sql)?.toString()
    private fun longOf(sql: String): Long = (objOf(sql) as Number).toLong()
    private fun objOf(sql: String): Any? {
        val rows = em.createNativeQuery(sql).resultList
        return if (rows.isEmpty()) null else rows[0]
    }
}
